- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: "120hrs"
    TRAINER: Sivareddy
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      #msg: "Course is Devops with AWS, Duration is 12hrs, Trainer is Sivareddy"
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"