- name: filter
  hosts: local
  connection: local
  tasks:
  - name: handle undefilne variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default ('Ramesh') }}"

  - name: convert list to string
    vars:
      fruits: "apple,mangoe,banana"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duaration: 10hrs
        trainer: Sivareddy
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convert list into item
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duaration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'Sivareddy'}
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"