- name: filter
  hosts: local
  connection: local
  tasks:
  - name: handle undefilne variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default ('Ramesh') }}"

  - name: convert list to string
    vars:
      fruits: "apple,mangoe,banana"
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split(',') }}"