- name: Install Apache
  hosts: webserver
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start and enable https service
      service:
      name: httpd
      state: started
      enabled: yes

